FROM nvcr.io/nvidia/pytorch:23.12-py3
ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    bash-completion \
    gnupg2 \
    cmake \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && pip install -U pip

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN pip install --no-cache-dir ultralytics

RUN pip uninstall -y opencv opencv-python opencv-contrib-python 2>/dev/null || true
RUN rm -rf /usr/local/lib/python3.10/dist-packages/cv2 /usr/local/lib/python3.10/dist-packages/opencv*
RUN pip install --no-cache-dir opencv-python-headless==4.12.0.88

RUN pip install --no-cache-dir onnxruntime==1.18.1
RUN pip install --no-cache-dir onnxruntime-gpu==1.18.1

RUN echo "sudo ldconfig" >> /home/${USERNAME}/.bashrc

USER $USERNAME
CMD ["bash"]
